import http from 'k6/http';
import { check, sleep, group } from 'k6';
import { Counter, Rate, Trend } from 'k6/metrics';
import { SharedArray } from 'k6/data';

// ─── Manifest (generated by generate_seed_data_v2.py) ────
const MANIFEST_PATH = __ENV.MANIFEST_PATH || '/tmp/coredisc-seed-v2/manifest.json';
let manifest;
try {
    manifest = JSON.parse(open(MANIFEST_PATH));
} catch (e) {
    // Fallback: minimal manifest for when file isn't available
    manifest = {
        hot_post_ids: [],
        circle_pairs: [],
        block_pairs: [],
        tiers: {
            T1: { member_ids: Array.from({ length: 10 }, (_, i) => i + 1) },
            T2: { member_ids: Array.from({ length: 100 }, (_, i) => i + 11) },
            T3: { member_ids: Array.from({ length: 200 }, (_, i) => i + 511) },
            T4: { member_ids: Array.from({ length: 50 }, (_, i) => i + 5011) },
        },
    };
}

// ─── Custom Metrics ──────────────────────────────────────
const feedDuration = new Trend('feed_duration', true);
const feedCoreDuration = new Trend('feed_core_duration', true);
const postDetailDuration = new Trend('post_detail_duration', true);
const postCreateDuration = new Trend('post_create_duration', true);
const commentCreateDuration = new Trend('comment_create_duration', true);
const hotPostDuration = new Trend('hot_post_duration', true);
const likeDuration = new Trend('like_duration', true);
const profileDuration = new Trend('profile_duration', true);
const notificationDuration = new Trend('notification_duration', true);
const searchDuration = new Trend('search_duration', true);
const questionDuration = new Trend('question_duration', true);
const followDuration = new Trend('follow_duration', true);
const errorRate = new Rate('error_rate');
const requestCount = new Counter('total_requests');

// ─── Configuration ───────────────────────────────────────
const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080';
const TEST_PASSWORD = 'testpass123a';

// Tier-based user pool sizes
const T1_USERS = 5;
const T2_USERS = 100;
const T3_USERS = 200;
const T4_USERS = 50;

// ─── Scenarios ───────────────────────────────────────────
export const options = {
    scenarios: {
        read_heavy: {
            executor: 'ramping-vus',
            startVUs: 0,
            stages: [
                { duration: '30s', target: 20 },    // warm-up
                { duration: '1m', target: 80 },      // ramp
                { duration: '2m', target: 150 },     // peak
                { duration: '5m', target: 150 },     // sustain
                { duration: '1m30s', target: 0 },    // cool-down
            ],
            gracefulRampDown: '10s',
            exec: 'readScenario',
        },
        write_operations: {
            executor: 'ramping-vus',
            startVUs: 0,
            stages: [
                { duration: '30s', target: 5 },
                { duration: '1m', target: 20 },
                { duration: '2m', target: 30 },
                { duration: '5m', target: 30 },
                { duration: '1m30s', target: 0 },
            ],
            gracefulRampDown: '10s',
            exec: 'writeScenario',
        },
    },
    thresholds: {
        feed_duration: ['p(95)<500'],
        feed_core_duration: ['p(95)<500'],
        post_detail_duration: ['p(95)<500'],
        post_create_duration: ['p(95)<1000'],
        comment_create_duration: ['p(95)<1000'],
        error_rate: ['rate<0.05'],
        http_req_duration: ['p(95)<2000'],
    },
};

// ─── Setup: Login tier-based user pool ───────────────────
export function setup() {
    console.log('Logging in tier-based user pool...');

    const userPool = [];
    let failures = 0;

    function loginUsers(tierName, ids, count) {
        const selected = ids.slice(0, count);
        let logged = 0;
        for (const id of selected) {
            const username = `loaduser_${id}`;
            const loginRes = http.post(
                `${BASE_URL}/api/auth/login`,
                JSON.stringify({ username, password: TEST_PASSWORD }),
                { headers: { 'Content-Type': 'application/json' } }
            );

            if (loginRes.status === 200) {
                const body = JSON.parse(loginRes.body);
                userPool.push({
                    tier: tierName,
                    username,
                    memberId: body.result.id,
                    accessToken: body.result.accessToken,
                });
                logged++;
            } else {
                failures++;
                if (failures <= 5) {
                    console.log(`Login failed for ${username}: ${loginRes.status}`);
                }
            }
        }
        console.log(`  ${tierName}: ${logged}/${count} logged in`);
    }

    loginUsers('T1', manifest.tiers.T1.member_ids, T1_USERS);
    loginUsers('T2', manifest.tiers.T2.member_ids, T2_USERS);
    loginUsers('T3', manifest.tiers.T3.member_ids, T3_USERS);
    loginUsers('T4', manifest.tiers.T4.member_ids, T4_USERS);

    console.log(`Total: ${userPool.length} users logged in (${failures} failures)`);

    return {
        users: userPool,
        hotPostIds: manifest.hot_post_ids,
    };
}

// ─── Read Scenario (80% of traffic) ─────────────────────
export function readScenario(data) {
    const { users, hotPostIds } = data;
    if (!users || users.length === 0) return;

    const user = users[__VU % users.length];
    const headers = {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${user.accessToken}`,
    };

    const scenario = weightedRandom([
        { weight: 25, fn: () => scenarioFeedAll(headers) },
        { weight: 10, fn: () => scenarioFeedCore(headers) },
        { weight: 15, fn: () => scenarioPostDetail(headers) },
        { weight: 10, fn: () => scenarioProfile(headers, user) },
        { weight: 15, fn: () => scenarioNotifications(headers) },
        { weight: 10, fn: () => scenarioQuestions(headers) },
        { weight: 5, fn: () => scenarioSearch(headers) },
        { weight: 5, fn: () => scenarioComments(headers) },
        { weight: 5, fn: () => scenarioHotPost(headers, hotPostIds) },
    ]);

    scenario();

    // Log-normal think time: median ~1s, range 0.5-2.2s
    sleep(logNormalSleep(0, 0.5, 0.5, 2.2));
}

// ─── Write Scenario (20% of traffic) ────────────────────
export function writeScenario(data) {
    const { users } = data;
    if (!users || users.length === 0) return;

    const user = users[__VU % users.length];
    const headers = {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${user.accessToken}`,
    };

    const scenario = weightedRandom([
        { weight: 25, fn: () => scenarioCreatePost(headers) },
        { weight: 25, fn: () => scenarioCreateComment(headers) },
        { weight: 20, fn: () => scenarioLikeUnlike(headers) },
        { weight: 15, fn: () => scenarioFollowUnfollow(headers, user) },
        { weight: 15, fn: () => scenarioNotificationRead(headers) },
    ]);

    scenario();

    // Longer think time for write ops
    sleep(logNormalSleep(0.5, 0.8, 1.0, 4.5));
}

// ─── Read Scenarios ──────────────────────────────────────

function scenarioFeedAll(headers) {
    group('Feed ALL', () => {
        const res = http.get(`${BASE_URL}/api/posts?feedType=ALL&size=10`, {
            headers,
            tags: { name: 'GET /api/posts?feedType=ALL' },
        });
        requestCount.add(1);
        feedDuration.add(res.timings.duration);
        const ok = check(res, { 'feed ALL 200': (r) => r.status === 200 });
        errorRate.add(!ok);

        // Pagination
        if (res.status === 200) {
            try {
                const body = JSON.parse(res.body);
                if (body.result && body.result.hasNext && body.result.nextCursor) {
                    const p2 = http.get(
                        `${BASE_URL}/api/posts?feedType=ALL&size=10&cursor=${body.result.nextCursor}`,
                        { headers, tags: { name: 'GET /api/posts?feedType=ALL (page2)' } }
                    );
                    requestCount.add(1);
                    feedDuration.add(p2.timings.duration);
                    errorRate.add(p2.status !== 200);
                }
            } catch (_) {}
        }
    });
}

function scenarioFeedCore(headers) {
    group('Feed CORE', () => {
        const res = http.get(`${BASE_URL}/api/posts?feedType=CORE&size=10`, {
            headers,
            tags: { name: 'GET /api/posts?feedType=CORE' },
        });
        requestCount.add(1);
        feedCoreDuration.add(res.timings.duration);
        const ok = check(res, { 'feed CORE 200': (r) => r.status === 200 });
        errorRate.add(!ok);
    });
}

function scenarioPostDetail(headers) {
    group('PostDetail', () => {
        const feedRes = http.get(`${BASE_URL}/api/posts?feedType=ALL&size=10`, {
            headers,
            tags: { name: 'GET /api/posts' },
        });
        requestCount.add(1);

        if (feedRes.status === 200) {
            try {
                const body = JSON.parse(feedRes.body);
                const posts = body.result && body.result.posts;
                if (posts && posts.length > 0) {
                    const post = posts[Math.floor(Math.random() * posts.length)];
                    const detailRes = http.get(`${BASE_URL}/api/posts/${post.postId}`, {
                        headers,
                        tags: { name: 'GET /api/posts/{postId}' },
                    });
                    requestCount.add(1);
                    postDetailDuration.add(detailRes.timings.duration);
                    const ok = check(detailRes, { 'post detail 200': (r) => r.status === 200 });
                    errorRate.add(!ok);
                }
            } catch (_) {}
        }
    });
}

function scenarioProfile(headers, user) {
    group('Profile', () => {
        const profileRes = http.get(`${BASE_URL}/api/members/my-home`, {
            headers,
            tags: { name: 'GET /api/members/my-home' },
        });
        requestCount.add(1);
        profileDuration.add(profileRes.timings.duration);
        errorRate.add(profileRes.status !== 200);

        // Other user profile
        const otherId = Math.floor(Math.random() * 500) + 1;
        const otherRes = http.get(`${BASE_URL}/api/members/my-home/loaduser_${otherId}`, {
            headers,
            tags: { name: 'GET /api/members/my-home/{username}' },
        });
        requestCount.add(1);
        errorRate.add(otherRes.status !== 200);

        const followersRes = http.get(`${BASE_URL}/api/followers`, {
            headers,
            tags: { name: 'GET /api/followers' },
        });
        requestCount.add(1);
        errorRate.add(followersRes.status !== 200);
    });
}

function scenarioNotifications(headers) {
    group('Notifications', () => {
        const unreadRes = http.get(`${BASE_URL}/api/notifications/unread`, {
            headers,
            tags: { name: 'GET /api/notifications/unread' },
        });
        requestCount.add(1);
        notificationDuration.add(unreadRes.timings.duration);
        errorRate.add(unreadRes.status !== 200);

        const listRes = http.get(`${BASE_URL}/api/notifications?size=10`, {
            headers,
            tags: { name: 'GET /api/notifications' },
        });
        requestCount.add(1);
        notificationDuration.add(listRes.timings.duration);
        errorRate.add(listRes.status !== 200);
    });
}

function scenarioQuestions(headers) {
    group('Questions', () => {
        const categoryId = Math.floor(Math.random() * 20) + 1;
        const basicRes = http.get(
            `${BASE_URL}/api/questions/basic?categoryId=${categoryId}`,
            { headers, tags: { name: 'GET /api/questions/basic' } }
        );
        requestCount.add(1);
        questionDuration.add(basicRes.timings.duration);
        errorRate.add(basicRes.status !== 200);

        const selectedRes = http.get(`${BASE_URL}/api/questions/selected`, {
            headers,
            tags: { name: 'GET /api/questions/selected' },
        });
        requestCount.add(1);
        questionDuration.add(selectedRes.timings.duration);
        errorRate.add(selectedRes.status !== 200);
    });
}

function scenarioSearch(headers) {
    group('Search', () => {
        const keywords = ['nick', 'user', 'load', 'test'];
        const keyword = keywords[Math.floor(Math.random() * keywords.length)];
        const res = http.get(
            `${BASE_URL}/api/search/members?keyword=${encodeURIComponent(keyword)}`,
            { headers, tags: { name: 'GET /api/search/members' } }
        );
        requestCount.add(1);
        searchDuration.add(res.timings.duration);
        errorRate.add(res.status !== 200);
    });
}

function scenarioComments(headers) {
    group('Comments', () => {
        // Get a post from feed, then fetch its comments
        const feedRes = http.get(`${BASE_URL}/api/posts?feedType=ALL&size=10`, {
            headers,
            tags: { name: 'GET /api/posts' },
        });
        requestCount.add(1);

        if (feedRes.status === 200) {
            try {
                const body = JSON.parse(feedRes.body);
                const posts = body.result && body.result.posts;
                if (posts && posts.length > 0) {
                    const post = posts[Math.floor(Math.random() * posts.length)];
                    // NOTE: CommentController path bug - @RestController("/api/") is bean name
                    // Actual path is /posts/{postId}/comments (not /api/posts/...)
                    const commentsRes = http.get(
                        `${BASE_URL}/posts/${post.postId}/comments?size=10`,
                        { headers, tags: { name: 'GET /posts/{postId}/comments' } }
                    );
                    requestCount.add(1);
                    errorRate.add(commentsRes.status !== 200);
                }
            } catch (_) {}
        }
    });
}

function scenarioHotPost(headers, hotPostIds) {
    group('HotPost', () => {
        if (!hotPostIds || hotPostIds.length === 0) return;

        const postId = hotPostIds[Math.floor(Math.random() * hotPostIds.length)];
        const res = http.get(`${BASE_URL}/api/posts/${postId}`, {
            headers,
            tags: { name: 'GET /api/posts/{postId} (hot)' },
        });
        requestCount.add(1);
        hotPostDuration.add(res.timings.duration);
        const ok = check(res, { 'hot post 200': (r) => r.status === 200 });
        errorRate.add(!ok);
    });
}

// ─── Write Scenarios ─────────────────────────────────────

function scenarioCreatePost(headers) {
    group('CreatePost', () => {
        const payload = {
            publicity: 'OFFICIAL',
            dailyWho: 'ALONE',
            dailyWhere: 'HOME',
            dailyWhat: 'REST',
            dailyDetail: '부하 테스트 중 생성된 게시물입니다.',
            answers: [
                {
                    answerOrder: 1,
                    type: 'TEXT',
                    textContent: '오늘도 열심히 하루를 보냈다.',
                },
            ],
        };

        const res = http.post(`${BASE_URL}/api/posts`, JSON.stringify(payload), {
            headers,
            tags: { name: 'POST /api/posts' },
        });
        requestCount.add(1);
        postCreateDuration.add(res.timings.duration);
        const ok = check(res, {
            'post create 2xx': (r) => r.status >= 200 && r.status < 300,
        });
        errorRate.add(!ok);
    });
}

function scenarioCreateComment(headers) {
    group('CreateComment', () => {
        // Get a post to comment on
        const feedRes = http.get(`${BASE_URL}/api/posts?feedType=ALL&size=10`, {
            headers,
            tags: { name: 'GET /api/posts' },
        });
        requestCount.add(1);

        if (feedRes.status === 200) {
            try {
                const body = JSON.parse(feedRes.body);
                const posts = body.result && body.result.posts;
                if (posts && posts.length > 0) {
                    const post = posts[Math.floor(Math.random() * posts.length)];
                    const commentPayload = { content: '부하 테스트 댓글입니다.' };

                    // NOTE: CommentController path bug
                    const res = http.post(
                        `${BASE_URL}/posts/${post.postId}/comments`,
                        JSON.stringify(commentPayload),
                        { headers, tags: { name: 'POST /posts/{postId}/comments' } }
                    );
                    requestCount.add(1);
                    commentCreateDuration.add(res.timings.duration);
                    const ok = check(res, {
                        'comment create 2xx': (r) => r.status >= 200 && r.status < 300,
                    });
                    errorRate.add(!ok);
                }
            } catch (_) {}
        }
    });
}

function scenarioLikeUnlike(headers) {
    group('Like/Unlike', () => {
        const feedRes = http.get(`${BASE_URL}/api/posts?feedType=ALL&size=10`, {
            headers,
            tags: { name: 'GET /api/posts' },
        });
        requestCount.add(1);

        if (feedRes.status === 200) {
            try {
                const body = JSON.parse(feedRes.body);
                const posts = body.result && body.result.posts;
                if (posts && posts.length > 0) {
                    const post = posts[Math.floor(Math.random() * posts.length)];

                    const likeRes = http.post(
                        `${BASE_URL}/api/posts/${post.postId}/likes`,
                        null,
                        { headers, tags: { name: 'POST /api/posts/{postId}/likes' } }
                    );
                    requestCount.add(1);
                    likeDuration.add(likeRes.timings.duration);
                    errorRate.add(likeRes.status !== 200 && likeRes.status !== 409);

                    sleep(0.3);

                    // Unlike to maintain data consistency
                    const unlikeRes = http.del(
                        `${BASE_URL}/api/posts/${post.postId}/likes`,
                        null,
                        { headers, tags: { name: 'DELETE /api/posts/{postId}/likes' } }
                    );
                    requestCount.add(1);
                    likeDuration.add(unlikeRes.timings.duration);
                    errorRate.add(unlikeRes.status !== 200 && unlikeRes.status !== 404);
                }
            } catch (_) {}
        }
    });
}

function scenarioFollowUnfollow(headers, user) {
    group('Follow/Unfollow', () => {
        // Follow a random T1-T2 user
        const targetId = Math.floor(Math.random() * 510) + 1;
        if (targetId === user.memberId) return;

        const followRes = http.post(
            `${BASE_URL}/api/follows/${targetId}`,
            null,
            { headers, tags: { name: 'POST /api/follows/{memberId}' } }
        );
        requestCount.add(1);
        followDuration.add(followRes.timings.duration);
        // 409 = already following
        errorRate.add(followRes.status !== 200 && followRes.status !== 409);

        sleep(0.5);

        // Unfollow to maintain consistency
        const unfollowRes = http.del(
            `${BASE_URL}/api/follows/${targetId}`,
            null,
            { headers, tags: { name: 'DELETE /api/follows/{memberId}' } }
        );
        requestCount.add(1);
        followDuration.add(unfollowRes.timings.duration);
        errorRate.add(unfollowRes.status !== 200 && unfollowRes.status !== 404);
    });
}

function scenarioNotificationRead(headers) {
    group('NotificationRead', () => {
        // Get notification list and mark as read
        const listRes = http.get(`${BASE_URL}/api/notifications?size=5`, {
            headers,
            tags: { name: 'GET /api/notifications' },
        });
        requestCount.add(1);

        if (listRes.status === 200) {
            try {
                const body = JSON.parse(listRes.body);
                const notifications = body.result && body.result.notifications;
                if (notifications && notifications.length > 0) {
                    const noti = notifications[0];
                    if (noti.notificationId) {
                        const readRes = http.patch(
                            `${BASE_URL}/api/notifications/${noti.notificationId}/read`,
                            null,
                            { headers, tags: { name: 'PATCH /api/notifications/{id}/read' } }
                        );
                        requestCount.add(1);
                        errorRate.add(readRes.status !== 200 && readRes.status !== 204);
                    }
                }
            } catch (_) {}
        }
    });
}

// ─── Teardown ────────────────────────────────────────────
export function teardown(data) {
    console.log(`Load test v2 completed. ${data.users.length} test users were used.`);
}

// ─── Utilities ───────────────────────────────────────────
function weightedRandom(items) {
    const totalWeight = items.reduce((sum, item) => sum + item.weight, 0);
    let random = Math.random() * totalWeight;
    for (const item of items) {
        random -= item.weight;
        if (random <= 0) return item.fn;
    }
    return items[items.length - 1].fn;
}

function logNormalSleep(mu, sigma, min, max) {
    // Box-Muller transform for normal distribution
    const u1 = Math.random();
    const u2 = Math.random();
    const z = Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
    const value = Math.exp(mu + sigma * z);
    return Math.min(Math.max(value, min), max);
}
